# Generated by Django 2.2.1 on 2019-06-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemnr', models.IntegerField(blank=True, max_length=6)),
                ('old_it_nr', models.CharField(blank=True, max_length=6)),
                ('jobcode', models.CharField(blank=True, max_length=10)),
                ('omschrijving', models.CharField(max_length=50)),
                ('REF_nbr', models.CharField(blank=True, max_length=15)),
                ('unit', models.CharField(blank=True, max_length=5)),
                ('eenheidsprijs', models.IntegerField(max_length=8)),
                ('ehp_onderaannemer', models.IntegerField(blank=True, max_length=8)),
                ('catergorie', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='werknemers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personeelsnummer', models.IntegerField(max_length=8)),
                ('naam', models.CharField(max_length=15)),
                ('voornaam', models.CharField(max_length=15)),
                ('skills', models.CharField(max_length=10)),
                ('functie', models.CharField(max_length=20)),
            ],
        ),
    ]
