# Generated by Django 2.2.1 on 2019-06-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EFF', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='catergorie',
            new_name='categorie',
        ),
    ]
