# Generated by Django 2.2.1 on 2019-06-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EFF', '0002_auto_20190612_1413'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='werknemers',
            new_name='werknemer',
        ),
    ]
